### ISSUE TITLE
十分鐘超詳細替 Hexo Next 開啟 Gitalk 留言版 | Welcome.Web.World

### ISSUE THREAD

**Issue by hsiangfeng** [hsiangfeng/hsiangfeng.github.io#12]
https://hsiangfeng.github.io/hexo/20191206/2397475810/ 

 最近決定將自己使用約快一年的 Disqus 換成 GitHub Gitalk，最主要原因是 Disqus 許多人留言常常收不到通知，發現的時候都已經過兩個禮拜甚至三個月以上，所以這一篇就來介紹如何快速開啟 Gitalk 吧!

**Comment by hsiangfeng** [comment]
Gitalk 測試

**Comment by RexHung0302** [comment]
請問如果不是使用 Next 佈景主題 該怎麼啟用呢？

**Comment by hsiangfeng** [comment]
> @RexHung0302
> 請問如果不是使用 Next 佈景主題 該怎麼啟用呢？

若不是使用 Next 主題的話，可以依照官方中文文檔來加入也是可以的，這邊以下提供一些參考連結給您唷~

[Gitalk 中文官方說明](https://hsiangfeng.github.io/hexo/20191206/2397475810/)

[Hexo 加上 gitalk](https://dwatow.github.io/2019/01-08-hexo/gitalk/)

**Comment by RexHung0302** [comment]
> @hsiangfeng
> > @RexHung0302
> > 請問如果不是使用 Next 佈景主題 該怎麼啟用呢？
> 
> 若不是使用 Next 主題的話，可以依照官方中文文檔來加入也是可以的，這邊以下提供一些參考連結給您唷~
> 
> [Gitalk 中文官方說明](https://hsiangfeng.github.io/hexo/20191206/2397475810/)
> 
> [Hexo 加上 gitalk](https://dwatow.github.io/2019/01-08-hexo/gitalk/)
> 

非常感謝 我發現我用的主題有 gitalk 但是加上去後都沒有反應 我再研究研究看看 非常感謝
