### ISSUE TITLE
連環轟炸的 [GitHub API] Deprecation notice for authentication via URL query parameters | Welcome.Web.World

### ISSUE THREAD

**Issue by hsiangfeng** [hsiangfeng/hsiangfeng.github.io#138]
https://hsiangfeng.github.io/hexo/20200206/1516602667/ 

 大概 109/02/02 開始我的信箱被連環轟炸一直收到 [GitHub API] Deprecation notice for authentication via URL query parameters，而這個主因其實是因為使用 Gitalk 所導致，所以這一篇就來紀錄一下該如何解決。

**Comment by hsiangfeng** [comment]
測試連環轟炸信件是否還在。

**Comment by GaisaiYuno** [comment]
試試能不能修好

**Comment by hsiangfeng** [comment]
> @GaisaiYuno
> 試試能不能修好

目前這一篇已經可以不用參照來修改 CDN 的部分，Gitalk 已經更新。

部落格更新到現在是已經沒有收到 GitHub 轟炸信。

**Comment by GaisaiYuno** [comment]
> > @GaisaiYuno
> > 試試能不能修好
> 
> 目前這一篇已經可以不用參照來修改 CDN 的部分，Gitalk 已經更新。
> 
> 部落格更新到現在是已經沒有收到 GitHub 轟炸信。


非常感謝，現在我也修好了
