### ISSUE TITLE
關於我從 Evernote 轉 Notion 這件事 | Welcome.Web.World

### ISSUE THREAD

**Issue by hsiangfeng** [hsiangfeng/hsiangfeng.github.io#178]
https://hsiangfeng.github.io/other/20200411/3690524648/ 

 Notion 是一款非常簡潔且非常好用的筆記軟體，好用到我直接拋棄我使用了將近快五年的 Evernote，所以這一篇來介紹一下 Notion 有什麼樣的魅力可以讓我拋棄吧。

**Comment by apostle-jiaxiang** [comment]
Hi，我也是從 Evernote 轉到 Notion 的使用者，
從六角學院的社團看到你的用心分享，
與你分享我的想法：

【限制裝置/記事大小限制/每月上傳總量限制】

這是 Evernote 讓使用者付費的手段。（使用者付費也很合理。）

Notion 其實也有相似的做法：

單一工作區域（workplace） 免費使用者最多只有 1000個區塊元素（ Block ），

超過就要付費。（個人版是 4鎂/每人每月每工作區域）

當 Notion 成為生活/工作流程的一環…… 這個 1000 Block 的上限蠻快就會碰到的。

而且有別於 Evernote 是單一帳號付費，全部 workplace/筆記本 都可以享用付費的待遇，

Notion 是依 workplace 來付費的。

換句話說，如果你有三個 workplace 的話，若想要三個 workpalce 都無限制就要付三倍的 $$。

　


因為這樣，我並不覺得這些情況是 Evernote 的缺點。

但我還是從 Evernote 轉過來了，而且每個月花的 $$ 還比 Evernote 多。

就因為 Notion 使用起來很舒服、很美，哈哈~

謝謝你讓 Notion 有更豐富的繁體中文資源 🥳

**Comment by hsiangfeng** [comment]
> @apostle-jiaxiang
> Hi，我也是從 Evernote 轉到 Notion 的使用者，
> 從六角學院的社團看到你的用心分享，
> 與你分享我的想法：
> 
> 【限制裝置/記事大小限制/每月上傳總量限制】
> 
> 這是 Evernote 讓使用者付費的手段。（使用者付費也很合理。）
> 
> Notion 其實也有相似的做法：
> 
> 單一工作區域（workplace） 免費使用者最多只有 1000個區塊元素（ Block ），
> 
> 超過就要付費。（個人版是 4鎂/每人每月每工作區域）
> 
> 當 Notion 成為生活/工作流程的一環…… 這個 1000 Block 的上限蠻快就會碰到的。
> 
> 而且有別於 Evernote 是單一帳號付費，全部 workplace/筆記本 都可以享用付費的待遇，
> 
> Notion 是依 workplace 來付費的。
> 
> 換句話說，如果你有三個 workplace 的話，若想要三個 workpalce 都無限制就要付三倍的 $$。
> 
> 　
> 
> 
> 因為這樣，我並不覺得這些情況是 Evernote 的缺點。
> 
> 但我還是從 Evernote 轉過來了，而且每個月花的 $$ 還比 Evernote 多。
> 
> 就因為 Notion 使用起來很舒服、很美，哈哈~
> 
> 謝謝你讓 Notion 有更豐富的繁體中文資源 🥳


Hi，
謝謝分享看法

沒有錯，這些並不能當作 Evernote 的缺點，畢竟使用者付費。

所以最後才會提到 Evernote 還是有它好用的地方，只是已經不太符合我的需求 😆

如果以金額來看的話，確實 Notion 金額是會比 Evernote 較高，
所以在後面也有補上如果使用學術帳號來使用 Notion 是可以多個空間免費升級到 Personal 的(目前我是升級三個 workspace 到 Personal)，正常來講應該只有一個 workspace 可以升級才對，所以當作小確幸（唉？

**Comment by billy8407** [comment]
> @apostle-jiaxiang
> Hi，我也是從 Evernote 轉到 Notion 的使用者，
> 從六角學院的社團看到你的用心分享，
> 與你分享我的想法：
> 
> 【限制裝置/記事大小限制/每月上傳總量限制】
> 
> 這是 Evernote 讓使用者付費的手段。（使用者付費也很合理。）
> 
> Notion 其實也有相似的做法：
> 
> 單一工作區域（workplace） 免費使用者最多只有 1000個區塊元素（ Block ），
> 
> 超過就要付費。（個人版是 4鎂/每人每月每工作區域）
> 
> 當 Notion 成為生活/工作流程的一環…… 這個 1000 Block 的上限蠻快就會碰到的。
> 
> 而且有別於 Evernote 是單一帳號付費，全部 workplace/筆記本 都可以享用付費的待遇，
> 
> Notion 是依 workplace 來付費的。
> 
> 換句話說，如果你有三個 workplace 的話，若想要三個 workpalce 都無限制就要付三倍的 $$。
> 
> 　
> 
> 
> 因為這樣，我並不覺得這些情況是 Evernote 的缺點。
> 
> 但我還是從 Evernote 轉過來了，而且每個月花的 $$ 還比 Evernote 多。
> 
> 就因為 Notion 使用起來很舒服、很美，哈哈~
> 
> 謝謝你讓 Notion 有更豐富的繁體中文資源 🥳


如果你的學校信箱還能使用的話，
可以改用教育版，
它提供免費Block
