### ISSUE TITLE
PixiJS V5 教學目錄內頁面錯誤

### ISSUE THREAD

**Issue by oToToT** [hsiangfeng/hsiangfeng.github.io#180]
- 「PixiJS V5 教學 (6) - Texture(2)」 的連結失效
- 「PixiJS V5 教學 (24) - AnimatedSprite」 的連結誤置為「PixiJS V5 教學 (23) - dat.GUI」的連結

感謝這系列的教學文章

**Comment by hsiangfeng** [comment]
感謝告知，我這邊結束後會一次調整~

**Comment by hsiangfeng** [comment]
目錄已修正，該系列已完結~
