### ISSUE TITLE
JavaScript製作分頁功能(使用Fetch) | Welcome.Web.World

### ISSUE THREAD

**Issue by hsiangfeng** [hsiangfeng/hsiangfeng.github.io#80]
https://hsiangfeng.github.io/javascript/20190505/1432256317/ 

 開網站會很長需要使用到分頁的功能，有些是在後端處理之後往前端丟，這種通常比較不擔心那麼多，只需要在資料庫做好相關設置就好了，可是如果今天後端將所有資料一次往前端丟那麼就要自己來刻分頁邏輯，所以寫一篇文章加強自己的分頁邏輯撰寫。

**Comment by Albertnotes** [comment]
Hello Ray

我是撰寫分頁，被您回應推薦觀看此筆記的學員
- 按鈕 pageBtn function 會只有19個
- 總計資料會只有95筆

```javascript
function pageBtn (page){
  let str = '';
  const total = page.pageTotal +1;  //這邊改了 +1 因為for 迴圈判斷式 是 <
  for(let i = 1; i < total; i++){
    str +=`<li class="page-item"><a class="page-link" href="#" data-page="${i}">${i}</a></li>`;
  };
  pageid.innerHTML = str;
}

// --- 下面這一段比較看不懂，想不出照著這整體函式跑，抓資料時怎麼會造成以下的狀況

  // 因為要避免當前頁數筆總頁數還要多，假設今天總頁數是 3 筆，就不可能是 4 或 5
  // 所以要在寫入一個判斷避免這種狀況。
  // 當"當前頁數"比"總頁數"大的時候，"當前頁數"就等於"總頁數"
  if (currentPage > pageTotal) {
    currentPage = pageTotal;
 }
```

**Comment by hsiangfeng** [comment]
> @Albertnotes
> Hello Ray
> 
> 我是撰寫分頁，被您回應推薦觀看此筆記的學員
> - 按鈕 pageBtn function 會只有19個
> - 總計資料會只有95筆
> 
> ```javascript
> function pageBtn (page){
>   let str = '';
>   const total = page.pageTotal +1;  //這邊改了 +1 因為for 迴圈判斷式 是 <
>   for(let i = 1; i < total; i++){
>     str +=`<li class="page-item"><a class="page-link" href="#" data-page="${i}">${i}</a></li>`;
>   };
>   pageid.innerHTML = str;
> }
> 
> // --- 下面這一段比較看不懂，想不出照著這整體函式跑，抓資料時怎麼會造成以下的狀況
> 
>   // 因為要避免當前頁數筆總頁數還要多，假設今天總頁數是 3 筆，就不可能是 4 或 5
>   // 所以要在寫入一個判斷避免這種狀況。
>   // 當"當前頁數"比"總頁數"大的時候，"當前頁數"就等於"總頁數"
>   if (currentPage > pageTotal) {
>     currentPage = pageTotal;
>  }
> ```
> 
> 
> 
> 
> 

沒有錯哦，因為這個分頁筆記已經相當齊全。

所以其實這一段有跟沒有是一樣的，但是在文章中有提到 `避免當前頁數筆總頁數還要多`，這一篇主要是要教你如何在不串接資料直接實作出一個分頁功能，因為當我們在拉取一個資料的時候往往可能無法確定後端往前端丟的資料數量，所以才會寫 ` if (currentPage > pageTotal) { currentPage = pageTotal; }` 來預防一些狀況，簡單來講有時候寫程式不是精簡就好，而是要避免可能會發生的狀況。
