### ISSUE TITLE
欠人教訓的提問 & 發問 | Welcome.Web.World

### ISSUE THREAD

**Issue by hsiangfeng** [hsiangfeng/hsiangfeng.github.io#93]
https://hsiangfeng.github.io/learnexp/20200112/1752686187/ 

身為一名工程師遇到問題並發問是一件非常常見的事情，但是許多人都會忽略所謂的「提問的智慧」，但是該如何提問的技巧又是一門學問，更不用說有些提問的方式真的很欠人教訓，甚至是翻白眼，所以就簡單來講一下該如何提問會比較洽當。

**Comment by ayugioh2003** [comment]
喔喔喔，google 年份搜尋可以用語法，我現在才知道 !

> 善用萬用關鍵字「」，使用可以取代你不確定的關鍵字，ex:「PHP 路徑」

BTW，這段話的萬用關鍵字是指 `*` 星號嗎？好像被 Markdown 語法轉成斜體字了。用 Markdown 的 ` `` ` 行內程式碼區塊，或是 html entity，可能能讓星號跑出來
* [Complete list of HTML entities - FreeFormatter.com](https://www.freeformatter.com/html-entities.html)

**Comment by hsiangfeng** [comment]
> @ayugioh2003
> 喔喔喔，google 年份搜尋可以用語法，我現在才知道 !
> 
> > 善用萬用關鍵字「」，使用可以取代你不確定的關鍵字，ex:「PHP 路徑」
> 
> BTW，這段話的萬用關鍵字是指 `*` 星號嗎？好像被 Markdown 語法轉成斜體字了。用 Markdown 的 ` `` ` 行內程式碼區塊，或是 html entity，可能能讓星號跑出來
> * [Complete list of HTML entities - FreeFormatter.com](https://www.freeformatter.com/html-entities.html)
> 
> 

沒有錯唷~

我忘記 MD 會針對 `*` 做修正，感謝提醒~
文章已經更新哩 :D
